import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import fs from 'fs';
import LottieIcon from "../components/LottieIcon"

import {useState, useEffect} from 'react'
const Home: NextPage = ({ lottieFiles }) => {
  return (
    <div className={styles.container} style={{ backgroundColor: "#efefef"}}>
      <Head>
        <title>Lottie viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: '100%', display: 'flex', flexDirection: 'row' }}>
        {lottieFiles && lottieFiles.map((file : object,i : number)=>
        <LottieIcon key={i}name={file.n} icon={file.u}/>)}
      </div>

    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const fileNames = fs.readdirSync('./public/lottie');
  console.log(fileNames)
  const lottieFiles = fileNames.map(file =>
    { return {n: file.split(".")[0], u: `/lottie/${file}`} })
  return { lottieFiles }
}

export default Home
